name: Deploy Lambda Function

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-southeast-2
  LAMBDA_FUNCTION_NAME: ajaibPuppeteer
  AWS_ROLE_TO_ASSUME: arn:aws:iam::311743913613:role/service-role/ajaibPuppeteer-role-wzh1ijx0

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy Lambda
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Use the appropriate Node.js version for your Lambda

    - name: Install dependencies
      run: |
        npm install
        npm ci  # Ensures a clean install (useful for CI/CD environments)

    - name: Configure AWS credentials (Assume Role)
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
        role-session-name: GitHubActionsLambdaDeployment

    - name: Zip the Lambda function
      run: zip -r function.zip . -x "*.git*" "*.github*"  # Exclude unnecessary files from the zip

    - name: Check if Lambda function exists
      id: check_lambda
      run: |
        if aws lambda get-function --function-name ${{ env.LAMBDA_FUNCTION_NAME }}; then
          echo "::set-output name=lambda_exists::true"
        else
          echo "::set-output name=lambda_exists::false"
        fi

    - name: Create or Update Lambda function
      run: |
        if [ "${{ steps.check_lambda.outputs.lambda_exists }}" == "false" ]; then
          echo "Creating Lambda function..."
          aws lambda create-function --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
            --runtime nodejs14.x --role ${{ env.AWS_ROLE_TO_ASSUME }} \
            --handler index.handler --zip-file fileb://function.zip
        else
          echo "Updating Lambda function..."
          aws lambda update-function-code \
            --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://function.zip --publish
        fi

    - name: Clean up
      run: rm function.zip
